{ pkgs, lib, ... }:
{
  # Companion theming/wallpaper-color tooling for the Hyprland setup
  # above (dcol/wallbash-style files), Linux-only and equally unverified.
  # Some of this (wallbash/, palette/) may be runtime-generated by the
  # theming scripts based on the current wallpaper -- worth revisiting
  # once the Linux host gets real testing -- but preserved as a plain
  # recursive copy for now rather than guessed at.
  xdg.configFile."hyprdots" = lib.mkIf pkgs.stdenv.isLinux {
    source = ./hyprdots;
    recursive = true;
  };
}
