return {
  -- Browsers
  ["Safari"] = ":safari:",
  ["Google Chrome"] = ":google_chrome:",
  ["Chromium"] = ":google_chrome:",
  ["Google Chrome Canary"] = ":google_chrome:",
  ["Firefox"] = ":firefox:",
  ["Firefox Developer Edition"] = ":firefox_developer_edition:",
  ["Firefox Nightly"] = ":firefox_developer_edition:",
  ["Microsoft Edge"] = ":microsoft_edge:",
  ["Arc"] = ":arc:",
  ["Brave Browser"] = ":brave_browser:",
  ["Vivaldi"] = ":vivaldi:",
  ["Orion"] = ":orion:",
  ["Orion RC"] = ":orion:",
  ["qutebrowser"] = ":qute_browser:",
  ["LibreWolf"] = ":libre_wolf:",
  ["Tor Browser"] = ":tor_browser:",
  ["Min"] = ":min_browser:",
  
  -- Development
  ["Xcode"] = ":xcode:",
  ["Code"] = ":code:",
  ["Code - Insiders"] = ":code:",
  ["VSCodium"] = ":vscodium:",
  ["Sublime Text"] = ":sublime_text:",
  ["Nova"] = ":nova:",
  ["Zed"] = ":zed:",
  ["Atom"] = ":atom:",
  ["WebStorm"] = ":web_storm:",
  ["IntelliJ IDEA"] = ":idea:",
  ["PyCharm"] = ":pycharm:",
  ["GoLand"] = ":goland:",
  ["Rider"] = ":rider:",
  ["JetBrains Rider"] = ":rider:",
  ["Android Studio"] = ":android_studio:",
  ["Neovim"] = ":vim:",
  ["Neovide"] = ":vim:",
  ["MacVim"] = ":vim:",
  ["Vim"] = ":vim:",
  ["VimR"] = ":vim:",
  ["Emacs"] = ":emacs:",
  ["Kakoune"] = ":kakoune:",
  
  -- Terminals
  ["Terminal"] = ":terminal:",
  ["iTerm"] = ":iterm:",
  ["Alacritty"] = ":alacritty:",
  ["kitty"] = ":kitty:",
  ["Hyper"] = ":hyper:",
  ["Warp"] = ":warp:",
  ["WezTerm"] = ":wezterm:",
  
  -- System & Utilities
  ["Finder"] = ":finder:",
  ["System Preferences"] = ":gear:",
  ["System Settings"] = ":gear:",
  ["Activity Monitor"] = ":gear:",
  ["Alfred"] = ":alfred:",
  ["Spotlight"] = ":spotlight:",
  ["Color Picker"] = ":color_picker:",
  ["CleanMyMac X"] = ":desktop:",
  ["1Password"] = ":one_password:",
  ["Bitwarden"] = ":bit_warden:",
  ["KeePassXC"] = ":kee_pass_x_c:",
  ["Keyboard Maestro"] = ":keyboard_maestro:",
  ["Setapp"] = ":setapp:",
  
  -- Communication
  ["Messages"] = ":messages:",
  ["WhatsApp"] = ":whats_app:",
  ["Discord"] = ":discord:",
  ["Discord Canary"] = ":discord:",
  ["Discord PTB"] = ":discord:",
  ["Telegram"] = ":telegram:",
  ["Signal"] = ":signal:",
  ["Slack"] = ":slack:",
  ["Microsoft Teams"] = ":microsoft_teams:",
  ["zoom.us"] = ":zoom:",
  ["Skype"] = ":skype:",
  ["FaceTime"] = ":face_time:",
  ["Element"] = ":element:",
  ["Mattermost"] = ":mattermost:",
  ["Zulip"] = ":zulip:",
  
  -- Mail
  ["Mail"] = ":mail:",
  ["Canary Mail"] = ":mail:",
  ["HEY"] = ":mail:",
  ["Mailspring"] = ":mail:",
  ["MailMate"] = ":mail:",
  ["Airmail"] = ":airmail:",
  ["Spark Desktop"] = ":spark:",
  ["Thunderbird"] = ":thunderbird:",
  
  -- Productivity & Notes
  ["Notes"] = ":notes:",
  ["Bear"] = ":bear:",
  ["Obsidian"] = ":obsidian:",
  ["Notion"] = ":notion:",
  ["Logseq"] = ":logseq:",
  ["Typora"] = ":text:",
  ["Drafts"] = ":drafts:",
  ["Joplin"] = ":joplin:",
  ["DEVONthink 3"] = ":devonthink3:",
  ["Anytype"] = ":anytype:",
  ["Tana"] = ":tana:",
  ["Grammarly Editor"] = ":grammarly:",
  
  -- Task Management
  ["Things"] = ":things:",
  ["Todoist"] = ":todoist:",
  ["Microsoft To Do"] = ":things:",
  ["OmniFocus"] = ":omni_focus:",
  ["Trello"] = ":trello:",
  ["Linear"] = ":linear:",
  ["ClickUp"] = ":click_up:",
  ["Reminders"] = ":reminders:",
  ["TickTick"] = ":tick_tick:",
  
  -- Calendar
  ["Calendar"] = ":calendar:",
  ["Fantastical"] = ":calendar:",
  ["Cron"] = ":calendar:",
  ["Amie"] = ":calendar:",
  
  -- Design & Media
  ["Figma"] = ":figma:",
  ["Sketch"] = ":sketch:",
  ["Affinity Designer"] = ":affinity_designer:",
  ["Affinity Designer 2"] = ":affinity_designer_2:",
  ["Affinity Photo"] = ":affinity_photo:",
  ["Affinity Photo 2"] = ":affinity_photo_2:",
  ["Affinity Publisher"] = ":affinity_publisher:",
  ["Affinity Publisher 2"] = ":affinity_publisher_2:",
  ["Blender"] = ":blender:",
  ["Zeplin"] = ":zeplin:",
  ["Miro"] = ":miro:",
  
  -- Video & Audio
  ["Final Cut Pro"] = ":final_cut_pro:",
  ["VLC"] = ":vlc:",
  ["mpv"] = ":mpv:",
  ["Music"] = ":music:",
  ["Spotify"] = ":spotify:",
  ["TIDAL"] = ":tidal:",
  ["Podcasts"] = ":podcasts:",
  ["Live"] = ":ableton:",
  ["OBS"] = ":obsstudio:",
  ["Audacity"] = ":audacity:",
  
  -- Office & Documents
  ["Microsoft Word"] = ":microsoft_word:",
  ["Microsoft Excel"] = ":microsoft_excel:",
  ["Microsoft PowerPoint"] = ":microsoft_power_point:",
  ["Pages"] = ":pages:",
  ["Numbers"] = ":numbers:",
  ["Keynote"] = ":keynote:",
  ["Preview"] = ":pdf:",
  ["Foxit PDF Reader"] = ":pdf:",
  ["Foxit Reader"] = ":pdf:",
  ["Skim"] = ":pdf:",
  
  -- Database & Development Tools
  ["Sequel Ace"] = ":sequel_ace:",
  ["Sequel Pro"] = ":sequel_pro:",
  ["GitHub Desktop"] = ":git_hub:",
  ["Tower"] = ":tower:",
  ["Docker"] = ":docker:",
  ["Docker Desktop"] = ":docker:",
  ["Insomnia"] = ":insomnia:",
  ["Replit"] = ":replit:",
  ["Cypress"] = ":cypress:",
  
  -- Virtualization & Remote
  ["Parallels Desktop"] = ":parallels:",
  ["VMware Fusion"] = ":vmware_fusion:",
  ["Citrix Workspace"] = ":citrix:",
  ["Citrix Viewer"] = ":citrix:",
  
  -- File Management & Cloud
  ["Dropbox"] = ":dropbox:",
  ["Transmit"] = ":transmit:",
  ["Folx"] = ":folx:",
  ["Raindrop.io"] = ":raindrop_io:",
  
  -- Reading & Research
  ["Calibre"] = ":book:",
  ["Reeder"] = ":reeder5:",
  ["Zotero"] = ":zotero:",
  ["Notability"] = ":notability:",
  
  -- Entertainment & Gaming
  ["League of Legends"] = ":league_of_legends:",
  ["Godot"] = ":godot:",
  ["Jellyfin Media Player"] = ":jellyfin:",
  
  -- System Apps
  ["App Store"] = ":app_store:",
  ["NordVPN"] = ":nord_vpn:",
  
  -- Special/Default
  ["default"] = ":default:",
  ["Default"] = ":default:",
}