{ pkgs, ... }:
{
  # Nix language tooling, available in every shell regardless of which
  # project is open -- no per-project devShell needed just to get an LSP,
  # a formatter, and basic lint/dead-code checks while editing .nix files.
  home.packages = [
    pkgs.nixd    # Language server (completion, goto-def, diagnostics).
    pkgs.nixfmt  # Canonical formatter (RFC 166 style).
    pkgs.statix  # Lints anti-patterns (e.g. `with` scope footguns).
    pkgs.deadnix # Flags dead/unused bindings.
  ];

  # fzf, zoxide, eza, and direnv already have full shell integration and
  # aliases hand-written and lazy-loaded in the (config-only) zsh setup --
  # functions/fzf.zsh, functions/cli-tools.zsh, lib/50-tools.zsh. zsh here
  # never sets programs.zsh.enable, so any enableZshIntegration output from
  # these modules would be generated but never actually sourced by the live
  # shell -- explicitly disabled on each so that isn't a second, invisible
  # source of truth waiting to surface if zsh's own management ever changes.
  # What each module still does today: install its package via Nix rather
  # than Homebrew (the live PATH already resolves the Nix profile ahead of
  # Homebrew, so this is the version that actually wins).
  programs.fzf = {
    enable = true;
    enableZshIntegration = false;

    # fzf and atuin both bind Ctrl-R in fish/nushell (the two shells here
    # that HM actually renders integration into); atuin is the established
    # history manager everywhere else in this config, so it keeps Ctrl-R
    # and fzf's own history widget steps aside for those two shells.
    historyWidget.fish.command = "";
    historyWidget.nushell.command = "";
  };

  programs.zoxide = {
    enable = true;
    enableZshIntegration = false;
  };

  programs.eza = {
    enable = true;
    enableZshIntegration = false;
  };

  programs.direnv = {
    enable = true;
    enableZshIntegration = false;
  };

  # No enableZshIntegration option and no dead config generated by leaving
  # these at their defaults -- just Nix-managed installs.
  programs.ripgrep.enable = true;
  programs.fd.enable = true;
}
