#!/usr/bin/env zsh
# shellcheck shell=zsh
# ============================================================================ #
#                      ███████╗██╗███╗   ██╗██╗████████╗
#                      ╚══███╔╝██║████╗  ██║██║╚══██╔══╝
#                        ███╔╝ ██║██╔██╗ ██║██║   ██║
#                       ███╔╝  ██║██║╚██╗██║██║   ██║
#                      ███████╗██║██║ ╚████║██║   ██║
#                      ╚══════╝╚═╝╚═╝  ╚═══╝╚═╝   ╚═╝
# ============================================================================ #
# +++++++++++++++++++++++++++++++ ZINIT SETUP ++++++++++++++++++++++++++++++++ #
# ============================================================================ #
#
# Zinit-based plugin loading that replaces the Oh-My-Zsh framework bootstrap.
# Keep startup synchronous work small and shift non-critical plugins to turbo.
#
# ============================================================================ #

# On HyDE: this file is loaded only when "HYDE_ZSH_NO_PLUGINS=1".
# The guard below is a safety net for direct sourcing.
if [[ "$HYDE_ENABLED" == "1" ]] && [[ "${HYDE_ZSH_NO_PLUGINS}" != "1" ]]; then
  # HyDE's shell.zsh handles plugins instead.
  return 0
fi

# Keep compfix (compaudit) enabled by default for safer completion loading.
# Set to "true" only if you explicitly want to skip security checks.
: "${ZSH_DISABLE_COMPFIX:=false}"
: "${ZSH_ENABLE_YOU_SHOULD_USE:=0}"
: "${ZSH_COMPINIT_CHECK_HOURS:=24}"

# Install and source Zinit from XDG data directory.
typeset -g ZINIT_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git"
if [[ ! -f "$ZINIT_HOME/zinit.zsh" ]]; then
  command mkdir -p "$ZINIT_HOME:h" 2>/dev/null
  if command -v git >/dev/null 2>&1; then
    command git clone --depth=1 https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME" 2>/dev/null || :
  fi
fi

if [[ ! -f "$ZINIT_HOME/zinit.zsh" ]]; then
  # Fallback to OMZ backup when Zinit isn't available (offline/first boot).
  typeset _zinit_module_dir="${${(%):-%x}:A:h}"
  typeset _zinit_omz_backup="${_zinit_module_dir}/20-omz.zsh.bak"
  if [[ "${ZSH_ZINIT_FALLBACK_OMZ:-1}" == "1" ]] && [[ -r "$_zinit_omz_backup" ]]; then
    print -u2 "Warning: zinit not available at $ZINIT_HOME (fallback: 20-omz.zsh.bak)"
    source "$_zinit_omz_backup"
    unset _zinit_module_dir _zinit_omz_backup
    return 0
  fi
  unset _zinit_module_dir _zinit_omz_backup
  print -u2 "Warning: zinit not available at $ZINIT_HOME"
  return 0
fi

source "$ZINIT_HOME/zinit.zsh"

# Optional optimization from Zinit docs: skip some disk checks on startup.
# Safe after first plugin install/update; disable with ZSH_ZINIT_OPTIMIZE_DISK_ACCESSES=0.
: "${ZSH_ZINIT_OPTIMIZE_DISK_ACCESSES:=1}"
if [[ "${ZSH_ZINIT_OPTIMIZE_DISK_ACCESSES}" == "1" ]]; then
  ZINIT[OPTIMIZE_OUT_DISK_ACCESSES]=1
fi

# Use XDG cache for completion dump to avoid framework-specific cache paths.
export ZSH_COMPDUMP="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/.zcompdump-$HOST"

# -----------------------------------------------------------------------------
# _zinit_compinit_periodic
# -----------------------------------------------------------------------------
# Reduce startup cost by running a full compinit only every N hours. Otherwise,
# reuse the cached dump with -C.
_zinit_compinit_periodic() {
  setopt localoptions noxtrace noverbose

  local cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
  local stamp_file="$cache_dir/compinit.last"
  local now epoch_last age_hours

  now=${EPOCHSECONDS:-$(date +%s)}
  epoch_last=0

  if [[ -f "$stamp_file" ]]; then
    if typeset -f _zsh_mtime >/dev/null 2>&1; then
      epoch_last="$(_zsh_mtime "$stamp_file")"
    elif [[ "${PLATFORM:-}" == "macOS" ]]; then
      epoch_last="$(stat -f %m "$stamp_file" 2>/dev/null || echo 0)"
    else
      epoch_last="$(stat -c %Y "$stamp_file" 2>/dev/null || echo 0)"
    fi
  fi

  [[ "$epoch_last" =~ ^[0-9]+$ ]] || epoch_last=0
  age_hours=$(( (now - epoch_last) / 3600 ))

  command mkdir -p "$cache_dir" "${ZSH_COMPDUMP:h}" 2>/dev/null
  autoload -Uz compinit

  # Fast path: reuse dump and skip security checks.
  if [[ -f "$ZSH_COMPDUMP" && $age_hours -lt ${ZSH_COMPINIT_CHECK_HOURS:-24} ]]; then
    compinit -C -d "$ZSH_COMPDUMP"
    return $?
  fi

  # Full init path.
  local insecure_mode="-i"
  [[ "$ZSH_DISABLE_COMPFIX" == true ]] && insecure_mode="-u"
  compinit "$insecure_mode" -d "$ZSH_COMPDUMP"
  local rc=$?

  if (( rc == 0 )); then
    touch "$stamp_file" 2>/dev/null || :
  fi
  return $rc
}

# -----------------------------------------------------------------------------
# _zinit_replay_compdefs
# -----------------------------------------------------------------------------
# Replay deferred compdefs generated by plugin snippets loaded before/after
# compinit (especially turbo plugins).
_zinit_replay_compdefs() {
  if typeset -f zicdreplay >/dev/null 2>&1; then
    zicdreplay -q
  elif typeset -f zinit >/dev/null 2>&1; then
    zinit cdreplay -q
  fi
}

# -----------------------------------------------------------------------------
# _zinit_bind_history_substring_keys
# -----------------------------------------------------------------------------
# Keybindings for zsh-history-substring-search plugin.
_zinit_bind_history_substring_keys() {
  bindkey '^[[A' history-substring-search-up
  bindkey '^[[B' history-substring-search-down

  [[ -n "${terminfo[kcuu1]-}" ]] && bindkey "${terminfo[kcuu1]}" history-substring-search-up
  [[ -n "${terminfo[kcud1]-}" ]] && bindkey "${terminfo[kcud1]}" history-substring-search-down

  bindkey -M vicmd 'k' history-substring-search-up
  bindkey -M vicmd 'j' history-substring-search-down

  HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1
  HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='bg=green,fg=black,bold'
  HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND='bg=red,fg=black,bold'
}

# Load OMZ snippets required by selected plugin snippets.
zinit snippet OMZL::completion.zsh
zinit snippet OMZL::theme-and-appearance.zsh

# Replaces OMZL::directories.zsh.
setopt auto_cd auto_pushd pushd_ignore_dups pushdminus
alias d='dirs -v | head -10'

# OMZ-compat function replacements are loaded from functions/omz-compat.zsh.

# Core OMZ plugin snippets loaded synchronously.
typeset -a _zinit_omz_plugins_sync=(
  git
  sudo
)
typeset -a _zinit_omz_plugins_deferred=(
  jsontools
  command-not-found
)
typeset _zinit_omz_plugin
for _zinit_omz_plugin in "${_zinit_omz_plugins_sync[@]}"; do
  zinit snippet "OMZP::${_zinit_omz_plugin}/${_zinit_omz_plugin}.plugin.zsh"
done
for _zinit_omz_plugin in "${_zinit_omz_plugins_deferred[@]}"; do
  zinit ice wait"1" lucid
  zinit snippet "OMZP::${_zinit_omz_plugin}/${_zinit_omz_plugin}.plugin.zsh"
done
unset _zinit_omz_plugin _zinit_omz_plugins_sync _zinit_omz_plugins_deferred

# Run compinit after synchronous snippets, then replay queued compdefs.
_zinit_compinit_periodic
_zinit_replay_compdefs

# ---------------------------- TURBO PLUGINS LOAD ---------------------------- #
# Common async plugin.
zinit ice wait"0" lucid atload"_zsh_autosuggest_start 2>/dev/null || true"
zinit light zsh-users/zsh-autosuggestions

if [[ "$PLATFORM" == "macOS" ]]; then
  zinit ice wait"1" lucid
  zinit light hlissner/zsh-autopair

  zinit ice wait"2" lucid
  zinit light fdellwing/zsh-bat

  if [[ "$ZSH_ENABLE_YOU_SHOULD_USE" == "1" ]]; then
    zinit ice wait"2" lucid
    zinit light MichaelAquilina/zsh-you-should-use
  fi
elif [[ "$PLATFORM" == "Linux" && "$ARCH_LINUX" == true ]]; then
  zinit ice wait"0" lucid
  zinit light chrissicool/zsh-256color

  zinit ice wait"1" lucid
  zinit snippet OMZP::fzf/fzf.plugin.zsh
fi

if [[ "$PLATFORM" == "macOS" ]] || [[ "$PLATFORM" == "Linux" && "$ARCH_LINUX" == true ]]; then
  # Keep this after autosuggestions.
  zinit ice wait"2" lucid atload"_zinit_bind_history_substring_keys"
  zinit light zsh-users/zsh-history-substring-search

  # Must stay last among async plugins.
  zinit ice wait"3" lucid atload"_zinit_replay_compdefs"
  zinit light zdharma-continuum/fast-syntax-highlighting
fi

# ============================================================================ #
# End of 20-zinit.zsh
