#!/bin/bash
 
options=(
	style=round
	width=5.0
	hidpi=on
	blur_radius=100.0
	background_color=0xff282828
	active_color=0xfffe8019
	active_color="gradient(top_left=0xfffe8019,bottom_right=0xffcc241d,top_right=0xfffb4934,bottom_left=0xfffabd2f)"
	inactive_color=0xff928374
	
	#Blacklisting some apps:
	blacklist="JetBrains Toolbox,C Lion,CLion Nova,IntelliJ IDEA Ultimate,PyCharm Professional Edition,GoLand,WebStorm,DataGrip,PhpStorm,Rider,RustRover-EAP"
)
	
borders "${options[@]}"