-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua

-- DAP: after all plugins are ready, load .vscode/launch.json if present and
-- add fallback launch/attach configs for C and C++ when none exist yet.
vim.api.nvim_create_autocmd("User", {
  pattern = "LazyDone",
  once = true,
  callback = function()
    local ok_dap, dap = pcall(require, "dap")
    if not ok_dap then return end

    local ok_vs, vscode = pcall(require, "dap.ext.vscode")
    if ok_vs then
      pcall(vscode.load_launchjs, nil, {
        codelldb = { "c", "cpp", "rust" },
        python   = { "python" },
      })
    end

    -- /Users/lcs-dev/LCS.Data is a symlink -> /Volumes/LCS.Data.
    -- The compiler embeds the symlink path in the debug info, but Neovim opens
    -- files via the real mount point. sourceMap tells codelldb to translate.
    local source_map = { ["/Users/lcs-dev/LCS.Data"] = "/Volumes/LCS.Data" }

    -- Prepend the sourceMap to every existing codelldb config so it applies
    -- also to the configs auto-generated by mason-nvim-dap.
    for _, ft in ipairs({ "c", "cpp", "rust" }) do
      for _, cfg in ipairs(dap.configurations[ft] or {}) do
        if cfg.type == "codelldb" and not cfg.sourceMap then
          cfg.sourceMap = source_map
        end
      end
    end

    -- Fallback configs: used only when no launch.json exists and mason-nvim-dap
    -- has not auto-generated configurations for these filetypes.
    for _, ft in ipairs({ "c", "cpp" }) do
      if not dap.configurations[ft] or #dap.configurations[ft] == 0 then
        dap.configurations[ft] = {
          {
            name        = "Launch (codelldb)",
            type        = "codelldb",
            request     = "launch",
            program     = function()
              return vim.fn.input("Executable: ", vim.fn.getcwd() .. "/", "file")
            end,
            cwd         = "${workspaceFolder}",
            stopOnEntry = false,
            terminal    = "integrated",
            sourceMap   = source_map,
          },
          {
            name    = "Attach to process (codelldb)",
            type    = "codelldb",
            request = "attach",
            pid     = require("dap.utils").pick_process,
            cwd     = "${workspaceFolder}",
          },
        }
      end
    end
  end,
})

vim.api.nvim_create_autocmd("FileType", {
  pattern = "markdown",
  callback = function()
    vim.opt_local.spell = true
    vim.opt_local.spelllang = "it,en"
  end,
})

vim.api.nvim_create_autocmd("FileType", {
  pattern = { "tex", "plaintex" },
  callback = function()
    vim.opt_local.conceallevel = 2
  end,
})
