#!/usr/bin/env lua

-- Load the sketchybar-package and prepare the helper binaries
require("helpers")
require("init")

-- Add AeroSpace workspace support
sbar.exec("sketchybar --add event aerospace_workspace_change")

-- Get workspace list and create indicators
local handle = io.popen("aerospace list-workspaces --all")
local workspaces = handle:read("*a")
handle:close()

for sid in workspaces:gmatch("%S+") do
    sbar.exec(string.format([[
        sketchybar --add item space.%s left \
            --subscribe space.%s aerospace_workspace_change \
            --set space.%s \
                background.color=0x44ffffff \
                background.corner_radius=5 \
                background.height=20 \
                background.drawing=off \
                label="%s" \
                label.color=0xffffffff \
                label.highlight_color=0xff9dd274 \
                label.font="sketchybar-app-font:Bold:14.0" \
                label.y_offset=-1 \
                click_script="aerospace workspace %s" \
                script="$CONFIG_DIR/plugins/aerospace.sh %s"
    ]], sid, sid, sid, sid, sid, sid))
end