{
  config,
  dotfilesRoot,
  pkgs,
  ...
}:
{
  # config uses ';' comments, which aren't valid TOML, and programs.cava
  # only offers a settings attrset (no raw extraConfig passthrough) --
  # routing this through its INI-style generator would risk the same
  # comment loss and casing issues found with btop. Linking everything
  # raw preserves the file (heavily documented with commented-out
  # defaults) exactly as-is.
  programs.cava.enable = true;

  xdg.configFile = {
    # Hyprdots' Linux wallbash integration edits the marked autogenerated tail
    # of this exact file with sed. Keep only that runtime-mutated file writable;
    # Darwin and the shader/theme assets remain immutable store-backed sources.
    "cava/config".source =
      if pkgs.stdenv.isLinux then
        config.lib.file.mkOutOfStoreSymlink "${dotfilesRoot}/home/cava/config"
      else
        ./config;
    "cava/frappe.cava".source = ./frappe.cava;
    "cava/shaders/bar_spectrum.frag".source = ./shaders/bar_spectrum.frag;
    "cava/shaders/pass_through.vert".source = ./shaders/pass_through.vert;
    "cava/shaders/northern_lights.frag".source = ./shaders/northern_lights.frag;
  };
}
